"use client";

import { Copy, Pin, Plus, Trash2 } from "lucide-react";
import { useState } from "react";
import { companies } from "@/lib/mock-data";
import type { ResearchMemo as ResearchMemoType } from "@/lib/types";

const storageKey = "note-research-memos";
export function ResearchMemo() {
  const [memos, setMemos] = useState<ResearchMemoType[]>(() => { if (typeof window === "undefined") return []; try { const saved = localStorage.getItem(storageKey); return saved ? JSON.parse(saved) as ResearchMemoType[] : []; } catch { localStorage.removeItem(storageKey); return []; } }); const [content, setContent] = useState(""); const [companyId, setCompanyId] = useState("");
  const update = (next: ResearchMemoType[]) => { setMemos(next); localStorage.setItem(storageKey, JSON.stringify(next)); };
  const add = () => { const trimmed = content.trim(); if (!trimmed) return; update([{ id: crypto.randomUUID(), content: trimmed, companyId: companyId || undefined, pinned: false, createdAt: new Date().toISOString() }, ...memos]); setContent(""); };
  const copy = async (memo: ResearchMemoType) => { await navigator.clipboard?.writeText(memo.content); };
  return <div><label htmlFor="research-memo" className="sr-only">리서치 메모</label><textarea id="research-memo" value={content} onChange={(event) => setContent(event.target.value)} placeholder="검토할 사항이나 공통 문구를 기록하세요." className="min-h-24 w-full resize-y rounded-md border border-slate-300 bg-white p-3 text-sm leading-5 text-slate-800 placeholder:text-slate-400" /><div className="mt-2 flex gap-2"><select aria-label="연결 기업" value={companyId} onChange={(event) => setCompanyId(event.target.value)} className="h-8 min-w-0 flex-1 rounded border border-slate-300 bg-white px-2 text-xs"><option value="">기업 및 주석 연결 (선택)</option>{companies.map((company) => <option key={company.id} value={company.id}>{company.name} · 무형자산 및 개발비</option>)}</select><button onClick={add} className="inline-flex h-8 items-center gap-1 rounded bg-[#123c78] px-2.5 text-xs font-semibold text-white hover:bg-[#0e3162]"><Plus className="h-3.5 w-3.5" />추가</button></div><div className="mt-5 space-y-2">{memos.length === 0 ? <p className="py-4 text-center text-xs text-slate-500">아직 저장한 메모가 없습니다.</p> : memos.sort((a, b) => Number(b.pinned) - Number(a.pinned)).map((memo) => <article key={memo.id} className="border border-slate-200 bg-white p-3"><div className="mb-2 flex items-center justify-between gap-2 text-[11px] text-slate-500"><span>{memo.companyId ? companies.find((item) => item.id === memo.companyId)?.name : "전체 기업"} · {new Date(memo.createdAt).toLocaleDateString("ko-KR")}</span><div className="flex"><button onClick={() => update(memos.map((item) => item.id === memo.id ? { ...item, pinned: !item.pinned } : item))} aria-label="메모 고정" className={memo.pinned ? "text-blue-700" : "text-slate-400 hover:text-slate-700"}><Pin className="h-3.5 w-3.5" /></button><button onClick={() => copy(memo)} aria-label="메모 복사" className="ml-2 text-slate-400 hover:text-slate-700"><Copy className="h-3.5 w-3.5" /></button><button onClick={() => update(memos.filter((item) => item.id !== memo.id))} aria-label="메모 삭제" className="ml-2 text-slate-400 hover:text-red-600"><Trash2 className="h-3.5 w-3.5" /></button></div></div><p className="whitespace-pre-wrap break-words text-sm leading-5 text-slate-700">{memo.content}</p></article>)}</div></div>;
}
