"use client";

import { Bookmark, Clock3, Star } from "lucide-react";
import { useState } from "react";
import type { SearchFilters } from "@/lib/types";

type View = "저장된 작업" | "최근 검색" | "즐겨찾기";
interface SavedSentence { id: string; title: string; text: string; company: string; }
export function StoredWork({ view, onOpenSearch }: { view: View; onOpenSearch: () => void }) { const [filters] = useState<SearchFilters[]>(() => readStorage("note-saved-filters")); const [sentences] = useState<SavedSentence[]>(() => readStorage("note-important-sentences")); const Icon = view === "즐겨찾기" ? Star : view === "최근 검색" ? Clock3 : Bookmark; return <section className="mx-auto max-w-4xl"><header className="border-b border-slate-200 pb-5"><p className="text-xs font-semibold tracking-[0.12em] text-blue-700">RESEARCH WORKSPACE</p><h1 className="mt-2 text-2xl font-semibold text-slate-950">{view}</h1><p className="mt-2 text-sm text-slate-600">{view === "즐겨찾기" ? "저장한 중요 문장을 검토합니다." : "저장한 검색 조건을 다시 열 수 있습니다."}</p></header><div className="mt-6 border border-slate-200 bg-white">{view === "즐겨찾기" ? sentences.length === 0 ? <Empty icon={Icon} text="저장한 중요 문장이 없습니다." /> : <ul>{sentences.map((sentence) => <li key={sentence.id} className="border-b border-slate-100 p-4 last:border-0"><p className="text-sm font-semibold text-slate-800">{sentence.company} · {sentence.title}</p><p className="mt-2 text-sm leading-6 text-slate-600">{sentence.text}</p></li>)}</ul> : filters.length === 0 ? <Empty icon={Icon} text="저장된 검색 조건이 없습니다." /> : <ul>{filters.map((filter, index) => <li key={`${filter.topic}-${index}`} className="flex items-center justify-between gap-4 border-b border-slate-100 p-4 last:border-0"><div><p className="text-sm font-semibold text-slate-800">{filter.year}년 {filter.reportType} · {filter.topic}</p><p className="mt-1 text-xs text-slate-500">비교기업 {filter.comparisonCompanies.length}개</p></div><button onClick={onOpenSearch} className="shrink-0 rounded border border-slate-300 px-3 py-1.5 text-xs font-medium text-slate-700 hover:bg-slate-50">검색 화면 열기</button></li>)}</ul>}</div></section>; }
function readStorage<T>(key: string): T[] { if (typeof window === "undefined") return []; try { return JSON.parse(localStorage.getItem(key) ?? "[]") as T[]; } catch { return []; } }
function Empty({ icon: Icon, text }: { icon: typeof Bookmark; text: string }) { return <div className="grid min-h-48 place-items-center text-center"><div><Icon className="mx-auto h-5 w-5 text-slate-400" /><p className="mt-2 text-sm text-slate-500">{text}</p></div></div>; }
